name: Prod Deployment Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  development:
    uses: Skatch-Skin-Match/skatch-aws-infrastructure/.github/workflows/dev.samdocker.yml@main
    with:
      apiName: Lambda
      applicationName: Skatch
      region: "us-west-2"
      tags: "Environment=Production ApplicationName=Skatch-App Name=Skatch-App CreatedBy=amit.heda"
      parameters: "EnvironmentName=Production"
      environment: "production"
      path: "./src/demo/"
      repositoryName: 'skatch/demo/python3.9'
      deploy: true
      dockerFile: "./src/demo/Dockerfile"
    secrets: inherit
   
     